controller_manager:
  ros__parameters:
  
    update_rate: 10
    # use_sim_time: true

    diffbot_controller:
      type: diff_drive_controller/DiffDriveController


diffbot_controller:
  ros__parameters:

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    
    wheel_separation: 0.297
    wheel_radius: 0.033
   
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
  
    open_loop: true
    position_feedback: false
    enable_odom_tf: true
